### ISSUE TITLE
Add a makefile

### ISSUE THREAD

**Issue by MattyJacques** [MattyJacques/BacklogManager#8]
Not everyone uses an IDE, we should have the option to have a makefile for those users/developers.

**Comment by GaryLeutheuser** [comment]
I'll take a shot at this.

**Comment by MattyJacques** [comment]
Awesome thanks, I tried to edit the makefile found [here ](https://stackoverflow.com/a/28663974/6115571) to include the Qt files however I couldn't figure it out. I've lived a very sheltered life within Visual Studio apparently.

**Comment by GaryLeutheuser** [comment]
Nice, I've been looking for a simple example of not having to list source files, thanks.

I'm having a bit of trouble installing the QT SDK, though. Is the free trial [here](https://www1.qt.io/download/) the only way?

**Comment by MattyJacques** [comment]
[https://www1.qt.io/download-open-source/#section-2](https://www1.qt.io/download-open-source/#section-2) you can also download the source from this page, you don't need the trial, that is for commercial use, What you need is the open source version which is at the above link.

**Comment by MattyJacques** [comment]
Fixed in Makefile #9
